apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    allow_anonymous true
    # Listener padrão para MQTT
    listener 1883
    # Novo listener para WebSockets na porta 9001
    listener 9001
    protocol websockets

---
# ---------------- Deployment -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto-broker
          image: eclipse-mosquitto:2.0.18
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 9001
              name: websockets
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-config

---
# -------------------- Service ----------------------
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 32333
    - name: websockets
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 32444
  type: NodePort