apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-kafka
  template:
    metadata:
      labels:
        app: consumer-kafka
    spec:
      containers:
        - name: consumer-kafka
          image: consumer-kafka:v1.1
          ports:
            - containerPort: 80