apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-kafka
  template:
    metadata:
      labels:
        app: producer-kafka
    spec:
      containers:
        - name: producer-kafka
          image: producer-kafka:v1.4
          ports:
            - containerPort: 3000